//category starts here
GET http://localhost:8000/categories
###
POST http://localhost:8000/categories
Content-Type: application/json

{
    "name":"Technology",
    "slug":"techss",
    "image":""
}
###
DELETE http://localhost:8000/categories
Content-Type: application/json  

{
"id":4
}
###
PUT http://localhost:8000/categories
Content-Type: application/json  

{
    "name":"updated",
    "slug":"updtd",
    "image":"",
    "id":10
}
###
GET http://localhost:8000/categories/2
###


//Products starts here 
GET http://localhost:8000/products
###
GET http://localhost:8000/products/11
###
POST http://localhost:8000/products
Content-Type: application/json

{
    "name":"product1",
    "slug":"prodsasa",
    "image":"",
    "id":2
}
###
DELETE http://localhost:8000/products
Content-Type: application/json  

{
"id":12
}
###
PUT http://localhost:8000/products
Content-Type: application/json  

{
    "name":"updated",
    "slug":"updtd",
    "image":"",
    "id":7
}
###