const genres = [
        "All",
        "Action",
        "Adventure",
        "Animation",
        "Biography",
        "Comedy",
        "Crime",
        "Documentary",
        "Drama",
        "Family",
        "Fantasy",
        "Film-noir",
        "History",
        "Horror",
        "Music",
        "Musical",
        "Mystery",
        "News",
        "Romance",
        "Sci-Fi",
        "Short",
        "Sport",
        "Talk-Show",
        "War",
        "Thriller",
        "Western"
    ]

    export default genres;
